// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3CoUU1A9OEYrn3oFIxjhK3fGnksOZMEs',
    appId: '1:220910735330:web:5550887ce75337b33a33bb',
    messagingSenderId: '220910735330',
    projectId: 'pill-pall-9b50f',
    authDomain: 'pill-pall-9b50f.firebaseapp.com',
    storageBucket: 'pill-pall-9b50f.firebasestorage.app',
    measurementId: 'G-WRMS1YP0VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChbt0O1HdAUlmqgmK51XtIf2aGd5ocxBg',
    appId: '1:220910735330:android:c19674a27f80e6a53a33bb',
    messagingSenderId: '220910735330',
    projectId: 'pill-pall-9b50f',
    storageBucket: 'pill-pall-9b50f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe2qAFVTOTPBZ1wpd_BBz-vpifE6s1EFI',
    appId: '1:220910735330:ios:24e430ce945793c03a33bb',
    messagingSenderId: '220910735330',
    projectId: 'pill-pall-9b50f',
    storageBucket: 'pill-pall-9b50f.firebasestorage.app',
    iosBundleId: 'com.example.newProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe2qAFVTOTPBZ1wpd_BBz-vpifE6s1EFI',
    appId: '1:220910735330:ios:24e430ce945793c03a33bb',
    messagingSenderId: '220910735330',
    projectId: 'pill-pall-9b50f',
    storageBucket: 'pill-pall-9b50f.firebasestorage.app',
    iosBundleId: 'com.example.newProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3CoUU1A9OEYrn3oFIxjhK3fGnksOZMEs',
    appId: '1:220910735330:web:0736b39b6e819e073a33bb',
    messagingSenderId: '220910735330',
    projectId: 'pill-pall-9b50f',
    authDomain: 'pill-pall-9b50f.firebaseapp.com',
    storageBucket: 'pill-pall-9b50f.firebasestorage.app',
    measurementId: 'G-ZSME9J5Y90',
  );

}